server:
  port: ${PORT:8080}

app:
  message: ${APP_MESSAGE:Hello, 12-Factor App!}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  security:
    enabled: false